extends:
  template: pipeline/templates/dotnet-k8s.yml
  parameters:
    appName: sample-api

    projectPath: src/Sample.Api/Sample.Api.csproj

    imageRepository: 448003890252.dkr.ecr.us-east-1.amazonaws.com/sample-api

    ciPoolName: Self-Hosted-Rancher

    helmReleaseName: sample-api

    environments:
      - name: dev
        azureEnvironment: develop
        poolName: Self-Hosted-Rancher
        namespace: sample-api-dev

      - name: hml
        azureEnvironment: homolog
        poolName: Self-Hosted-Rancher
        namespace: sample-api-hml

      - name: prd
        azureEnvironment: production
        poolName: Self-Hosted-Rancher
        namespace: sample-api-prd
